version: '3'

services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=pass
      - MYSQL_USER=user
      - MYSQL_DATABASE=my_db

networks:
  default:
    driver: bridge

volumes:
  mysql: