services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=pass
      - MYSQL_USER=user
      - MYSQL_DATABASE=my_db
      # Comma-separated list of additional databases to create
      # Example: MYSQL_MULTIPLE_DATABASES=app1_db,app2_db,test_db
      - MYSQL_MULTIPLE_DATABASES=${MYSQL_MULTIPLE_DATABASES:-}
    restart: unless-stopped

networks:
  default:
    driver: bridge

volumes:
  mysql_data:
    driver: local