version: '3'
services:
  telegraf:
    image: telegraf:1.18-alpine
    links:
      - influxdb
    depends_on:
      - influxdb
    ports:
      - '8125:8125'

  influxdb:
    image: influxdb:1.8-alpine
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb

networks:
  default:
    driver: bridge

volumes:
  influxdb_data: